config/routes.rb
Blogger::Application.routes.draw do
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
include ArticlesHelper



	def index
		#Cette méthode dit
		# à serveur/articles affiche tout ce qu'il y a
		# dans la Table Article
		@articles = Article.all
	end

	def show
		#Cette méthode dit
		# Affiche l'article qui est égal
		# identifiant
		@article = Article.find(params[:id])
	end
		#Cette méthode dit
		# Affiche la page new
	def new
		@article = Article.new
	end
		#Cette méthode dit
		# Crée et Sauve les valeurs saisies
  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to article_path(@article)
  end
 	def destroy
 		@article = Article.find(params[:id])
  		@article.destroy
  		redirect_to articles_path
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	# Cette action dit que params 
	# n'autorise que deux champs "title" et "body"
  def article_params
    params.require(:article).permit(:title, :body)
  end

end

app/views/articles/index.html.erb
<h1>Affiche tout les éléments de la Table Article</h1>

<ul id="articles">
	<% @articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article)%> <br>
			<%= article.body %>
		</li>
	<%end%>
</ul>
<br>
<%= link_to "Créer un nouvel article", new_article_path %>

app/views/articles/new.html.erb
<h1>Crééer un nouvel article.</h1>
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1>Affiche Un élément les éléments de la Table Article</h1>

			<h2><%= @article.title%> </h2> 
			<p><%= @article.body %> </p>
<%= link_to "<< Retour", articles_path %>

<!-- Cette inclusion ruby es la façon unique 
de supprimer une fiche c'est method: :delete
Cette methode doit retrouver dans le controler concerné
l'action def destroy 

--> 
<%= link_to "Supprime", 
		@article,
			method: :delete,
			data: {confirm: "Voulez vous vraiment supprimer cet article?", confirm: "T'es sur?"}
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>